-- Insert the list of entities into the "nagrade" table
INSERT INTO `nagrade` (`naziv_nagrade`)
VALUES
('Nagrada Grada Zagreba'),
('Vladimir Nazor'),
('Drago Gervais'),
('Ranko Marinković'),
('Grigor Vitez'),
('Goranov Vijenac'),
('Ivana Brlić-Mažuranić'),
('Goran za mlade pjesnike'),
('Ksaver Šandor Gjalski'),
('Sfera'),
('Visoka žuta žita'),
('Marin Držić'),
('Fra Lucijan Kordić'),
('Mato Lovrak'),
('Nagrada Hrvatske akademije znanosti i umjetnosti'),
('Albatros'),
('Josip i Ivan Kozarac'),
('Kvirinovi poetski susreti'),
('Nagrade Dana hrvatske knjige (Slavić, Judita, Davidias)'),
('Nagrada za najbolji neobjavljeni roman godine'),
('Iso Velikanović'),
('Kratka kajkavska proza'),
('Ovca u kutiji'),
('Anto Gardaš'),
('Dragan Plamenac'),
('Fran Galović'),
('Lapis Histriae'),
('Dani Franje Horvata Kiša'),
('roman@tportal.hr'),
('Zvane Črnja'),
('Milivoj Cvetnić'),
('Andrija Maurović'),
('Mali Marulić'),
('Artefakt'),
('BOOKtiga'),
('Ivan vitez Trnski'),
('Edo Budiša'),
('Kratka priča muzeja anđela'),
('Najbolja kratka priča strave'),
('Teatar.hr'),
('metaFORA'),
('Višnja Machiedo'),
('Zvonko'),
('Anđelko Novaković'),
('Dijana Klarić'),
('Janko Polić Kamov'),
('Najbolja priča FEKP-a'),
('Petrarca Fest'),
('Goran Bujić'),
('Marijina nagrada'),
('Mirko Kovač'),
('Stjepan Kranjčić'),
('Kitica'),
('Post Scriptum'),
('Stipan Bilić-Prcić'),
('Zvonimir Milčec'),
('Sedmica i Kritična masa'),
('Tin Ujević'),
('Julije Benešić'),
('Eva Verona'),
('Miroslav Krleža'),
('Dubravko Jelačić Bužimski; Nedjeljko Fabrio; Ljerka Car Matutinović; Sanja Pilić; Pavao Pavličić; Ludwig Bauer; Miro Gavran; Miroslav Slavko Mađer; Ljerka Car Matutinović;'),
('Antun Gustav Matoš'),
('August Šenoa'),
('Dragutin Tadijanović'),
('Ivan Kukuljević Sakcinski'),
('Josip Tabak - za najbolje prijevode'),
('Kaštelanske štorije'),
('Kiklop'),
('Mjesto radnje: Makarska'),
('Mladi lav'),
('Nagrada Stjepko Težak / Moje drago srce'),
('Na vrh jezika'),
('Nagrada Jutarnjeg lista'),
('Nagrada pasionske baštine'),
('Natječaj za rukopis romana za djecu i mlade'),
('Neretvanska maslina'),
('Priča se (p)o gradu'),
('Prozak'),
('Rikard Jorgovanić'),
('Tea Benčić Rimay'),
('T-portalova književna nagrada'),
('Libar za vajk'),
('Balkan Noir'),
('Fric'),
('Piširiši'),
('Konjanik'),
('Katarina Patačić'),
('Mali Galović'),
('Predrag Matvejević'),
('Zvonko Milković'),
('Stjepan Gulin'),
('Korzo slova');

-- Commit the changes
COMMIT;