-- Insert the list of "organizator" entities into the "organizator" table
INSERT INTO `nagrade` (`organizator`)
VALUES
('Grad Zagreb'),
('Republika Hrvatska (ministarstvo Kulture?)'),
('Grad Rijeka'),
('Večernji list'),
('Savez društava Naša djeca Hrvatske'),
('Goranovo proljeće'),
('Školska Knjiga'),
('Goranovo proljeće'),
('Društvo hrvatskih književnika i grad Zabok'),
('Društvo za znanstvenu fantastiku SFera'),
('Pjesnički susret u Drenovcima'),
('Ministarstvo kulture RH'),
('Društvo hrvatskih književnika'),
('Lovrakovi dani kulture'),
('HAZU'),
('Pučko otvoreno učilište Velika Gorica'),
('DHK; Vuk-Srijem. Žup'),
('Matica Hrvatska Sisak'),
('Društvo hrvatskih književnika'),
('V.B.Z.'),
('Ministarstvo kulture RH'),
('Časopis Kaj'),
('Knjiga u centru, ranije Autorska kuća'),
('Društvo hrvatskih književnika'),
('Hrvatsko muzikološko društvo'),
('Grad Koprivnica/DHK Podravsko-prigorski ogranak'),
('Forum Tomizza'),
('Općina Lobor'),
('tportal.hr'),
('Društvo hrvatskih književnika'),
('Društvo prijatelja knjige Milivoj Cvetnić'),
('Art 9 (udruga za očuvanje baštine i popularizaciju hrvatskog stripa)'),
('Gradsko kazalište lutaka Split i festival Mali Marulić'),
('Udruga 3. zmaj'),
('Gradska knjižnica Poreč'),
('Društvo hrvatskih književnika'),
('Istarska županija'),
('Muzej anđela'),
('Mala performerska scena/Freaky Friday'),
('teatar.hr'),
('Knjižnica Vladimira Nazora Zagreb'),
('P.E.N. centar'),
('Hrvatsko društvo književnika za djecu'),
('Zaklada NSK'),
('Hrvatski klub putnika'),
('Hrvatsko društvo pisaca'),
('Festival europske kratke priče/Centar za kreativno pisanje'),
(''), -- You can fill in the missing entry
('Hrvatsko književno društvo'),
('Muzej Anđela'),
('Udruga Mirko Kovač'),
('Udruga za promicanje znamenitih Križevčana "Dr. Stjepan Kranjčić"'),
('Hrvatsko društvo književnika za djecu i mlade'),
('Udruga Kultipraktik'),
('nagr'),
('Gornjogradski književni festival i obitelj Milčec'),
('Časopis Kritična Masa'),
('Društvo hrvatskih književnika'),
('Društvo hrvatskih književnika Ogranak slavonsko-baranjsko-srijemski i Matica hrvatska Ogranak Đakovo'),
('Hrvatsko knjižničarsko društvo'),
('Društvo hrvatskih književnika'),
('Jadranski književni susreti'),
('Matica hrvatska'),
('Matica hrvatska'),
('Zaklada HAZU'),
('Matica hrvatska'),
('Društvo hrvatskih književnih prevodilaca'),
('Gradska knjižnica Kaštela'),
('Sa(n)jam knjige u Istri'),
('Gradska knjižnica Makarska'),
('Crtani romani šou'),
('Matica hrvatska Ozalj/GKiČ Ivan Belostenac Ozalj'),
('Udruga Kultipraktik'),
('Jutarnji list'),
('DHK i Udruga Hrvatska pasionska baština'),
('Društvo hrvatskih književnika'),
('GKIČ Opuzen i Društvo hrvatskih književnika'),
('Gradska knjižnica Trogir'),
('Udruga Kultipraktik'),
('Hrvatsko zagorsko književno društvo / Općina Hum na Sutli'),
('Narodna knjižnica i  čitaonica Vlado Gotovac Sisak'),
('Hrvatski Telekom - tportal.hr'),
('Udruga Sanjam knjige u Istri'),
('Biblioteka Balkan Noir'),
('tjednik Express'),
('Hrvatskog društva književnika za djecu i mlade'),
('Pučko otvoreno učilište Zaprešić'),
('Varaždinsko književno društvo'),
('Koprivničko-križevačka županija'),
('Portal Radio Gornji grad'),
('Matica hrvatska'),
('Šibenska književna ura'),
('Društvo hrvatskih književnika');

-- Commit the changes
COMMIT;
